[package]
name = "windows-tray-battery-percent"
version = "0.1.0"
edition = "2021"

[features]
default = []
no-debug-output = []

[profile.release]
strip = true
lto = true
codegen-units = 1

[dependencies]
battery = "0.7.8"
image = "0.25.6"
tray-icon = "0.20.1"
winit = "0.30"
